name: Deploy Hugo to GitHub Pages

on:
  push:
    branches:
      
main  # replace with the name of the branch you push to

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      
name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0

      
name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.97.1'  # specify the Hugo version you are using

      
name: Build
      run: hugo --minify  # You can add other flags here if needed

      
name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public